name: LLM API CI/CD - Unit Tests

on: [push, pull_request]

jobs:
  # Run Unit Tests
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Unit Tests
        run: |
          docker build -t fastapirepo .
          docker run --rm -e OPENAI_ORG_ID=${{ secrets.OPENAI_ORG_ID }} -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} fastapirepo pytest